import sys
from PyQt5.QtWidgets import QApplication
from PyQt5 import QtCore, QtGui, QtWidgets
import os
import openpyxl as opXl
import scipy.interpolate
import numpy as np
import time
class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(529, 460)
        MainWindow.setMinimumSize(QtCore.QSize(529, 460))
        MainWindow.setMaximumSize(QtCore.QSize(529, 460))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.floorNum_label = QtWidgets.QLabel(self.centralwidget)
        self.floorNum_label.setGeometry(QtCore.QRect(120, 190, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.floorNum_label.setFont(font)
        self.floorNum_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.floorNum_label.setWordWrap(True)
        self.floorNum_label.setObjectName("floorNum_label")
        self.floorNum_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.floorNum_LE.setGeometry(QtCore.QRect(310, 200, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.floorNum_LE.setFont(font)
        self.floorNum_LE.setText("")
        self.floorNum_LE.setAlignment(QtCore.Qt.AlignCenter)
        self.floorNum_LE.setObjectName("floorNum_LE")
        self.Intro_label = QtWidgets.QLabel(self.centralwidget)
        self.Intro_label.setEnabled(True)
        self.Intro_label.setGeometry(QtCore.QRect(50, 380, 411, 111))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.Intro_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Intro_label.setFont(font)
        self.Intro_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.Intro_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Intro_label.setTextFormat(QtCore.Qt.PlainText)
        self.Intro_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Intro_label.setWordWrap(True)
        self.Intro_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Intro_label.setObjectName("Intro_label")
        self.p1HIB_Butt = QtWidgets.QPushButton(self.centralwidget)
        self.p1HIB_Butt.setGeometry(QtCore.QRect(190, 290, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.p1HIB_Butt.setFont(font)
        self.p1HIB_Butt.setStyleSheet("background-color: rgb(128, 172, 238);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.p1HIB_Butt.setObjectName("p1HIB_Butt")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 541, 460))
        self.label.setMinimumSize(QtCore.QSize(529, 460))
        palette = QtGui.QPalette()
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label.setPalette(palette)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 88, 221, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Intro_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.Intro_label_2.setEnabled(True)
        self.Intro_label_2.setGeometry(QtCore.QRect(50, 0, 411, 111))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.Intro_label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Intro_label_2.setFont(font)
        self.Intro_label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.Intro_label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Intro_label_2.setTextFormat(QtCore.Qt.PlainText)
        self.Intro_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Intro_label_2.setWordWrap(True)
        self.Intro_label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Intro_label_2.setObjectName("Intro_label_2")
        self.Intro_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.Intro_label_3.setEnabled(True)
        self.Intro_label_3.setGeometry(QtCore.QRect(50, 30, 411, 111))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.Intro_label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Intro_label_3.setFont(font)
        self.Intro_label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.Intro_label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Intro_label_3.setTextFormat(QtCore.Qt.PlainText)
        self.Intro_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Intro_label_3.setWordWrap(True)
        self.Intro_label_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Intro_label_3.setObjectName("Intro_label_3")
        self.label.raise_()
        self.floorNum_label.raise_()
        self.floorNum_LE.raise_()
        self.Intro_label.raise_()
        self.p1HIB_Butt.raise_()
        self.Intro_label_2.raise_()
        self.Intro_label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nurosis 1 of 3"))
        self.floorNum_label.setText(_translate("MainWindow", "Input The total Number of Floor in Your Building  "))
        self.Intro_label.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400; color:#ff00ff;\">my name is nayeem </span></p></body></html>"))
        self.Intro_label.setText(_translate("MainWindow", "I am Nurosis made by Arifuzzaman Nayeem \n"
"mdarifuzzamannayeem@pc.ce.buet.ac.bd \n"
"+8801914875631\n"
""))
        self.p1HIB_Butt.setText(_translate("MainWindow", "Click Here to continue "))
        self.Intro_label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400; color:#ff00ff;\">my name is nayeem </span></p></body></html>"))
        self.Intro_label_2.setText(_translate("MainWindow", "Wind Load Calculator"))
        self.Intro_label_3.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400; color:#ff00ff;\">my name is nayeem </span></p></body></html>"))
        self.Intro_label_3.setText(_translate("MainWindow", "According to BNBC 1993"))
class Ui_MainWindow2(object):
    def setFloorNumber(self, floorNum):
        self.floorNumber = floorNum
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(529, 460)
        MainWindow.setMinimumSize(QtCore.QSize(529, 460))
        MainWindow.setMaximumSize(QtCore.QSize(529, 460))
        MainWindow.setIconSize(QtCore.QSize(25, 25))
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calc_butt = QtWidgets.QPushButton(self.centralwidget)
        self.calc_butt.setGeometry(QtCore.QRect(250, 400, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.calc_butt.setFont(font)
        self.calc_butt.setStyleSheet("background-color: rgb(172, 200, 244);")
        self.calc_butt.setObjectName("calc_butt")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(260, 110, 78, 141))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sif_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sif_label.setFont(font)
        self.sif_label.setWordWrap(True)
        self.sif_label.setObjectName("sif_label")
        self.verticalLayout_3.addWidget(self.sif_label)
        self.rb_1_25 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rb_1_25.setFont(font)
        self.rb_1_25.setObjectName("rb_1_25")
        self.verticalLayout_3.addWidget(self.rb_1_25)
        self.rb_1_00 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rb_1_00.setFont(font)
        self.rb_1_00.setObjectName("rb_1_00")
        self.verticalLayout_3.addWidget(self.rb_1_00)
        self.rb_0_80 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rb_0_80.setFont(font)
        self.rb_0_80.setObjectName("rb_0_80")
        self.verticalLayout_3.addWidget(self.rb_0_80)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(260, 10, 71, 94))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Exp_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Exp_label.setFont(font)
        self.Exp_label.setWordWrap(True)
        self.Exp_label.setObjectName("Exp_label")
        self.verticalLayout_4.addWidget(self.Exp_label)
        self.rb_A = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rb_A.setFont(font)
        self.rb_A.setObjectName("rb_A")
        self.verticalLayout_4.addWidget(self.rb_A)
        self.rb_B = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rb_B.setFont(font)
        self.rb_B.setObjectName("rb_B")
        self.verticalLayout_4.addWidget(self.rb_B)
        self.rb_C = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rb_C.setFont(font)
        self.rb_C.setObjectName("rb_C")
        self.verticalLayout_4.addWidget(self.rb_C)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(250, 270, 211, 96))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.yWidth_LE = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.yWidth_LE.setFont(font)
        self.yWidth_LE.setText("")
        self.yWidth_LE.setAlignment(QtCore.Qt.AlignCenter)
        self.yWidth_LE.setObjectName("yWidth_LE")
        self.gridLayout.addWidget(self.yWidth_LE, 1, 1, 1, 1)
        self.windVelo_LE = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.windVelo_LE.setFont(font)
        self.windVelo_LE.setText("")
        self.windVelo_LE.setAlignment(QtCore.Qt.AlignCenter)
        self.windVelo_LE.setObjectName("windVelo_LE")
        self.gridLayout.addWidget(self.windVelo_LE, 2, 1, 1, 1)
        self.ywidth_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ywidth_label.setFont(font)
        self.ywidth_label.setWordWrap(True)
        self.ywidth_label.setObjectName("ywidth_label")
        self.gridLayout.addWidget(self.ywidth_label, 1, 0, 1, 1)
        self.xWidth_LE = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.xWidth_LE.setFont(font)
        self.xWidth_LE.setText("")
        self.xWidth_LE.setAlignment(QtCore.Qt.AlignCenter)
        self.xWidth_LE.setObjectName("xWidth_LE")
        self.gridLayout.addWidget(self.xWidth_LE, 0, 1, 1, 1)
        self.WindVelo_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.WindVelo_label.setFont(font)
        self.WindVelo_label.setWordWrap(False)
        self.WindVelo_label.setObjectName("WindVelo_label")
        self.gridLayout.addWidget(self.WindVelo_label, 2, 0, 1, 1)
        self.xWidth_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.xWidth_label.setFont(font)
        self.xWidth_label.setWordWrap(True)
        self.xWidth_label.setObjectName("xWidth_label")
        self.gridLayout.addWidget(self.xWidth_label, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 230, 420))
        self.tableWidget.setMinimumSize(QtCore.QSize(230, 420))
        self.tableWidget.setMaximumSize(QtCore.QSize(230, 420))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setStyleSheet("gridline-color: rgb(0, 0, 0);")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(self.floorNumber)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(115)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(115)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        for i in range (self.floorNumber):
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            item.setFlags(QtCore.Qt.ItemIsEnabled)
            self.tableWidget.setItem(i, 0, item)
        for i in range (self.floorNumber):
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(i, 1, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 541, 460))
        self.label.setMinimumSize(QtCore.QSize(529, 460))
        palette = QtGui.QPalette()
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label.setPalette(palette)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 88, 221, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 20, 171, 171))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("picture1.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.calc_butt.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.verticalLayoutWidget_4.raise_()
        self.layoutWidget.raise_()
        self.tableWidget.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nurosis 2 of 3"))
        self.calc_butt.setText(_translate("MainWindow", "Ciick Here to continue "))
        self.sif_label.setText(_translate("MainWindow", "Structural Importance factor "))
        self.rb_1_25.setText(_translate("MainWindow", "1.25"))
        self.rb_1_00.setText(_translate("MainWindow", "1.00"))
        self.rb_0_80.setText(_translate("MainWindow", "0.80"))
        self.Exp_label.setText(_translate("MainWindow", "Exposure"))
        self.rb_A.setText(_translate("MainWindow", "A"))
        self.rb_B.setText(_translate("MainWindow", "B"))
        self.rb_C.setText(_translate("MainWindow", "C"))
        self.ywidth_label.setText(_translate("MainWindow", "Y-dir Width (m)"))
        self.WindVelo_label.setText(_translate("MainWindow", "Wind Velocity (kM/h)"))
        self.xWidth_label.setText(_translate("MainWindow", "X-dir Width (m)"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Floor Nos."))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Floor Height(m)"))
        for i  in range (self.floorNumber):
            if i ==0:
                item = self.tableWidget.item(i, 0)
                item.setText(_translate("MainWindow", "Ground Floor"))
            elif i ==1:
                item = self.tableWidget.item(i, 0)
                item.setText(_translate("MainWindow", "1st Floor"))
            elif i ==2:
                item = self.tableWidget.item(i, 0)
                item.setText(_translate("MainWindow", "2nd Floor"))
            elif i ==3:
                item = self.tableWidget.item(i, 0)
                item.setText(_translate("MainWindow", "3rd Floor"))
            else:
                item = self.tableWidget.item(i, 0)
                item.setText(_translate("MainWindow", str(i)+"th Floor"))
class Ui_MainWindow3(object):
    def setRowNumber(self, rowNum):
        self.rowNumber = rowNum
    def setResult(self,result):
        self.xdir,self.ydir = result
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(529, 460)
        MainWindow.setMinimumSize(QtCore.QSize(529, 460))
        MainWindow.setMaximumSize(QtCore.QSize(529, 460))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 541, 460))
        self.label.setMinimumSize(QtCore.QSize(529, 460))
        palette = QtGui.QPalette()
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 88, 221))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label.setPalette(palette)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 88, 221, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 90, 250, 331))
        self.tableWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(self.rowNumber)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(124)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(124)
        for i in range (self.rowNumber):
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            item.setFlags(QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsSelectable)
            self.tableWidget.setItem(i, 0, item)
        for i in range (self.rowNumber):
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            item.setFlags(QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsSelectable)
            self.tableWidget.setItem(i, 1, item)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 30, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(62, 129, 229);")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 30, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(184, 209, 246);")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(270, 90, 250, 331))
        self.tableWidget_2.setMinimumSize(QtCore.QSize(250, 0))
        self.tableWidget_2.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(self.rowNumber)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(124)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(124)
        for i in range(self.rowNumber):
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            item.setFlags(QtCore.Qt.ItemIsEnabled)
            self.tableWidget_2.setItem(i, 0, item)
        for i in range(self.rowNumber):
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            item.setFlags(QtCore.Qt.ItemIsEnabled)
            self.tableWidget_2.setItem(i, 1, item)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 430, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nurosis 3 of 3"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Floor No"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Force (kN)"))
        self.label_2.setText(_translate("MainWindow", "Wind On X Dir "))
        self.label_3.setText(_translate("MainWindow", "Wind On Y Dir "))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Floor No"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Force (kN)"))
        self.label_4.setText(_translate("MainWindow", "Done "))
        for i  in range (self.rowNumber):
            if i ==0:
                item = self.tableWidget.item(i, 0)
                item.setText(_translate("MainWindow", "Ground Floor"))
                item = self.tableWidget_2.item(i, 0)
                item.setText(_translate("MainWindow", "Ground Floor"))
            elif i ==1:
                item = self.tableWidget.item(i, 0)
                item.setText(_translate("MainWindow", "1st Floor"))
                item = self.tableWidget_2.item(i, 0)
                item.setText(_translate("MainWindow", "1st Floor"))

            elif i ==2:
                item = self.tableWidget.item(i, 0)
                item.setText(_translate("MainWindow", "2nd Floor"))
                item = self.tableWidget_2.item(i, 0)
                item.setText(_translate("MainWindow", "2nd Floor"))

            elif i ==3:
                item = self.tableWidget.item(i, 0)
                item.setText(_translate("MainWindow", "3rd Floor"))
                item = self.tableWidget_2.item(i, 0)
                item.setText(_translate("MainWindow", "3rd Floor"))

            else:
                item = self.tableWidget.item(i, 0)
                item.setText(_translate("MainWindow", str(i)+"th Floor"))
                item = self.tableWidget_2.item(i, 0)
                item.setText(_translate("MainWindow", str(i) + "th Floor"))

        for i  in range (self.rowNumber):
            item = self.tableWidget.item(i, 1)
            item.setText(_translate("MainWindow", str(round(self.xdir[i],2))))
            item = self.tableWidget_2.item(i, 1)
            item.setText(_translate("MainWindow", str(round(self.ydir[i],2))))
class DisplaySoft1(QtWidgets.QMainWindow, Ui_MainWindow1):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.show()
        self.p1HIB_Butt.clicked.connect(self.HeightInput)
        self.p1HIB_Butt.clicked.connect(self.changeWindow)

    def HeightInput(self):
        n = int(self.floorNum_LE.text())
        self.close()
        return n
    def changeWindow(self):
        self.ShowApp = DisplaySoft2(self.HeightInput())
class DisplaySoft2(QtWidgets.QMainWindow, Ui_MainWindow2):
    def __init__(self, floorNumber):
        super().__init__()
        self.setFloorNumber(floorNumber)
        self.setupUi(self)
        self.show()
        self.calc_butt.clicked.connect(self.Result)
        self.calc_butt.clicked.connect(self.changeWindow2)

    def rowcount(self):
        x = self.tableWidget.rowCount()
        return x
    def Result(self):
        if self.rb_1_25.isChecked() == True:
            ci = 1.25
        elif self.rb_1_00.isChecked() == True:
            ci = 1.00
        elif self.rb_0_80.isChecked() == True:
            ci = 0.8
        #########################################
        if self.rb_A.isChecked() == True:
            exp = "A"
        elif self.rb_B.isChecked() == True:
            exp = "B"
        elif self.rb_C.isChecked() == True:
            exp = "C"
        #######################################
        x_dir_width = float(self.xWidth_LE.text())
        y_dir_width = float(self.yWidth_LE.text())
        wind_vlocity = float(self.windVelo_LE.text())
        #########################################################
        wb_obj = opXl.load_workbook("Cz 1993.xlsx")

        def OneD_Colarray(Sheet_object, column_number, rowStart, rowRnd):
            array = []
            for i in range(rowStart, rowRnd + 1):
                a = Sheet_object.cell(row=i, column=column_number).value
                array.append(a)
            return array
        def OneD_Rowarray(Sheet_object, row_number, colStart, colEnd):
            array = []
            for i in range(colStart, colEnd + 1):
                a = Sheet_object.cell(row=row_number, column=i).value
                array.append(a)
            return array
        def TwoD_array(Sheet_name, max_rowNumer, max_ColNumber):
            TwoD_arrray = []
            for row in range(3, max_rowNumer + 1):
                row_array = []
                for col in range(3, max_ColNumber + 1):
                    row_array.append(Sheet_name.cell(row, col).value)
                TwoD_arrray.append(row_array)
            return TwoD_arrray
        ## CZ & CG sheet Calculation Start
        def CzandCg(User_Height, Exposure):
            wb_obj = opXl.load_workbook("Cz 1993.xlsx")
            Sh_ob_CZ = wb_obj["CZ"]
            max_row_CZ = Sh_ob_CZ.max_row

            Sh_ob_CG = wb_obj["CG"]
            max_row_CG = Sh_ob_CG.max_row
            Height = OneD_Colarray(Sh_ob_CZ, 1, 2, max_row_CZ)
            cZ_A = OneD_Colarray(Sh_ob_CZ, 2, 2, max_row_CZ)
            cZ_B = OneD_Colarray(Sh_ob_CZ, 3, 2, max_row_CZ)
            cZ_C = OneD_Colarray(Sh_ob_CZ, 4, 2, max_row_CZ)

            cG_A = OneD_Colarray(Sh_ob_CG, 2, 2, max_row_CG)
            cG_B = OneD_Colarray(Sh_ob_CG, 3, 2, max_row_CG)
            cG_C = OneD_Colarray(Sh_ob_CG, 4, 2, max_row_CG)

            X = Height

            if Exposure == "A":
                YZ = cZ_A
                YG = cG_A


            elif Exposure == "B":
                YZ = cZ_B
                YG = cG_B


            elif Exposure == "C":
                YZ = cZ_C
                YG = cG_C


            else:
                print("Error: You have enter A,B or C Only")

            cZ_interp = scipy.interpolate.interp1d(X, YZ)
            Cz = (cZ_interp(User_Height))

            cG_interp = scipy.interpolate.interp1d(X, YG)
            CG = (cG_interp(User_Height[len(User_Height) - 1]))
            return Cz, CG
         ## CZ & CG sheet Calculation End
        ## CP calculation Start
        def Cp(LbyBRatio, HbyBRaion):
            Sh_ob_CP = wb_obj["Cp"]
            max_row_CP = Sh_ob_CP.max_row
            max_col_CP = Sh_ob_CP.max_column
            l_by_b = OneD_Rowarray(Sh_ob_CP, 2, 3, max_col_CP)
            h_by_b = OneD_Colarray(Sh_ob_CP, 2, 3, max_row_CP)
            cP = TwoD_array(Sh_ob_CP, max_row_CP, max_col_CP)
            cP_interp = scipy.interpolate.interp2d(l_by_b, h_by_b, cP)
            CP = float(cP_interp(LbyBRatio, HbyBRaion))
            return CP

        ## ## CP calculation end
        ## Each Floor Height From Ground calculation Start##
        def FloorHeightFromGround(IndiviualFloorHeight):
            a = 0
            B = []
            for i in range(len(IndiviualFloorHeight)):
                a = IndiviualFloorHeight[i] + a
                B.append(a)
            A = np.array(B)
            return A

        ## Each Floor Height From Ground calculation End##
        ## Start Effective Wind Area Calculation of each Floor strat ##
        def WindArea(IndiviualFloorHeight, length):
            A = []
            a = 0
            for i in range(len(IndiviualFloorHeight) - 1):
                a = (IndiviualFloorHeight[i + 1] / 2) + (IndiviualFloorHeight[i] / 2)
                A.append(a)
            a = IndiviualFloorHeight[len(IndiviualFloorHeight) - 1] / 2
            A.append(a)

            Area = np.array(A) * length
            return Area

        ## Start Effective Wind Area Calculation of each Floor End ##

        # User Input Data
        #print("Hello \nI am Nurosis made by Arifuzzaman Nayeem \nmdarifuzzamannayeem@pc.ce.buet.ac.bd \n+8801914875631")
       # print("I will help you in your Complex calculation of Wind Load in Building\nPlease follow the instruction: \n\n ")
        #time.sleep(3)
        n = self.floorNumber
        Ifh = []
        a = 0
        for i in range(0, n):
            a = float(self.tableWidget.item(i,1).text())
            Ifh.append(a)

        # print("")
        a = 0
        for i in range(len(Ifh)):
            a = Ifh[i] + a
        Total_height = a
        print("Total Height of your Building is " + str(round(Total_height, 2)) + " m")
        Exp = exp
        X_dir_width = x_dir_width
        Y_dir_width = y_dir_width
        ##Ifh = str(input("Enter the  Indivisual Floor Height in  meter: "))
        # length = X_dir_width
        # width = Y_dir_width
        Vb = wind_vlocity
        Ci = ci
        # Exp = "A"
        # length = 20   ##m
        # width = 20   ##m
        # Total_height  = 16 ##m

        # Ifh = [4,3,3,3,3] ##m
        Floor_Height = FloorHeightFromGround(Ifh)
        # Vb = 210 #kM/h
        Cc = 4.72 * 10 ** -5  ## Pz will be kPa and V is kM/h
        # Ci = 1

        Z, G = CzandCg(Floor_Height, Exp)
        # print(Z,G)
        ## Wind on Y Direction
        ly = Y_dir_width
        by = X_dir_width
        hy = Total_height
        lb_ratioY = ly / by
        hb_ratioY = hy / by
        CPY = (Cp(lb_ratioY, hb_ratioY))
        Pz_Y = np.array(Cc * Ci * Vb ** 2 * Z * G * CPY)  ##kPa
        Fz_Y = WindArea(Ifh, by) * Pz_Y  ##kN
        ## Wind on X Direction
        lx = X_dir_width
        bx = Y_dir_width
        hx = Total_height
        lb_ratioX = lx / bx
        hb_ratioX = hx / bx
        CPX = (Cp(lb_ratioX, hb_ratioX))

        Pz_X = np.array(Cc * Ci * Vb ** 2 * Z * G * CPX)  ##kPa
        Fz_X = WindArea(Ifh, bx) * Pz_X  ##kN

        print("\nWind on X direction \n")
        print(Fz_X)

        print("\nWind on Y direction \n")
        print(Fz_Y)

        print("\n\nDone.\n")

        self.close()
        return Fz_X,Fz_Y
        ##################################################################
    def changeWindow2(self):
        self.ShowApp = DisplaySoft3(self.rowcount(),self.Result())
class DisplaySoft3(QtWidgets.QMainWindow, Ui_MainWindow3):
    def __init__(self,rownumber,result):
        super().__init__()
        self.setRowNumber(rownumber)
        self.setResult(result)
        self.setupUi(self)
        self.show()

app = QApplication(sys.argv)
ShowApp = DisplaySoft1()
sys.exit(app.exec_())